name: Deploy to GCS

on:
  push:
    branches:
      - main  # Run this workflow only on the main branch

jobs:
  deploy-to-gcs:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      # Step 3: Authenticate and sync files to GCS
      - name: Deploy files to GCS
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

          # Ensure bucket URL is correct
          BUCKET_NAME="${{ secrets.GCP_BUCKET_NAME }}"
          gsutil -m rsync -R ./ gs://$BUCKET_NAME

      # Step 4: Configure public access for GCS bucket
      - name: Enable public read access
        run: |
          BUCKET_NAME="${{ secrets.GCP_BUCKET_NAME }}"
          gsutil iam ch allUsers:objectViewer gs://$BUCKET_NAME

      # Step 5: Configure the bucket for static website hosting
      - name: Set up website hosting
        run: |
          BUCKET_NAME="${{ secrets.GCP_BUCKET_NAME }}"
          gsutil web set -m index.html -e 404.html gs://$BUCKET_NAME
